version: '3.9'

services:
  app:
    build: .  # 指定 Dockerfile 的路径（当前目录）
    container_name: pingpong
    command: tail -f /dev/null  # 添加此行让容器保持运行
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 12GB
    volumes:
      - ./data:/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
